//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesProduct
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public long Product_Price { get; set; }
        public int Product_Quantity { get; set; }
        public string Product_Description { get; set; }
        public int Id_Provider { get; set; }
    
        public virtual SalesProvider SalesProvider { get; set; }
    }
}
